name: Test

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: leafo/gh-actions-lua@v13
      with:
        luaVersion: "luajit-2.1"

    - uses: leafo/gh-actions-luarocks@v6

    - name: Show Lua environment
      run: |
        lua -v
        luarocks --version

    - name: Install dependencies
      run: |
        luarocks install busted
        luarocks install dkjson
        luarocks install luacheck

    - name: Run lint
      run: luacheck --codes .

    - name: Run tests
      run: busted spec
